# Generated by Django 2.1.7 on 2019-02-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vores',
            new_name='votes',
        ),
    ]
